name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user information
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Determine Version Bump
        id: version
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          if [[ $COMMIT_MESSAGE == "feat:"* ]]; then
            echo "::set-output name=version-bump::minor"
          elif [[ $COMMIT_MESSAGE == "fix:"* ]]; then
            echo "::set-output name=version-bump::patch"
          elif [[ $COMMIT_MESSAGE == "rel:"* ]]; then
            echo "::set-output name=version-bump::major"
          else
            echo "::set-output name=version-bump::none"
          fi
        shell: bash

      - name: Bump Version and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_BUMP=$(echo ${{ steps.version.outputs.version-bump }})
          if [ "$VERSION_BUMP" == "minor" ]; then
            npm version minor
          elif [ "$VERSION_BUMP" == "patch" ]; then
            npm version patch
          elif [ "$VERSION_BUMP" == "major" ]; then
            npm version major
          fi

          TAG=$(git describe --abbrev=0)
          TITLE="Release $TAG"
          BODY="Release notes for version $TAG"
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/releases" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{
              \"tag_name\": \"${TAG}\",
              \"name\": \"${TITLE}\",
              \"body\": \"${BODY}\",
              \"draft\": false,
              \"prerelease\": false
            }"
          git push --follow-tags

      