name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user information
        run: |
          git config --global user.name "urmasmuld"
          git config --global user.email "urmas.muldmaa@gmail.com"
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Determine the new version
        run: |
          current_version=$(node -p -e "require('./package.json').version")
          new_version=$(npm version patch)
          echo "Current Version: $current_version"
          echo "New Version: $new_version"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Commit and push version change
        run: |
          git commit -a -m "Bump version to $new_version"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
