name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bump version and create release
        run: |
          npm version --no-git-tag-version <version>
          # Replace '<version>' with 'major', 'minor', or 'patch' depending on your changes
          # Use any other logic here for determining version bump

      - name: Push changes and tags
        run: |
          git push --follow-tags
          git push origin HEAD:main
