name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user information
        run: |
          git config --global user.name "urmasmuld"
          git config --global user.email "urmas.muldmaa@gmail.com"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npm run release

      - name: Push changes and tags
        run: |
          git push --follow-tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(git describe --tags)
          body=$(git log $(git describe --abbrev=0 --tags $tag)..HEAD --pretty=format:"* %s%n%b")
          echo "Creating release for tag: $tag"
          echo "::set-env name=RELEASE_TAG::$tag"
          echo "::set-env name=RELEASE_BODY::$body"
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
          RELEASE_NAME: Release ${{ env.RELEASE_TAG }}
          RELEASE_BODY: ${{ env.RELEASE_BODY }}

