name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user information
        run: |
          git config --global user.name "urmasmuld"
          git config --global user.email "urmas.muldmaa@gmail.com"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bump Version and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use npm version to increment the package.json version
          npm version patch -m "Bump version to %s" # You can use "major" or "minor" instead of "patch" for different releases
          TAG=$(git describe --abbrev=0)
          TITLE="Release $TAG"
          BODY="Release notes for version $TAG"
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/releases" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{
              \"tag_name\": \"${TAG}\",
              \"name\": \"${TITLE}\",
              \"body\": \"${BODY}\",
              \"draft\": false,
              \"prerelease\": false
            }"
          git push --follow-tags

      - name: Restore package.json
        run: |
          git checkout package.json
